### ISSUE TITLE
Ability to create NAT rules on the T0 router

### ISSUE THREAD

**Issue by nvpnathan** [terraform-providers/terraform-provider-nsxt#5] opened 2018-04-11 13:02 UTC
Need the ability to create NAT rules on the T0 router, not just the T1.

**Comment by DRuggeri** [comment] 2018-04-12 17:04
I've done this by providing t0 as the logical_router_id with the current version of the provider:
```
{
  "data": {
    "nsxt_logical_tier0_router": {
      "t0": {
        "display_name": "foo"
      }
    }
  },
  "resource": {
    "nsxt_nat_rule": {
      "director-inbound": {
        "action": "DNAT",
        "enabled": true,
        "logical_router_id": "${data.nsxt_logical_tier0_router.t0.id}",
        "match_destination_network": "10.1.2.3",
        "translated_network": "192.168.1.2"
      }
    }
  }
}
```

**Comment by yasensim** [comment] 2018-04-12 17:59
hi @nvpnathan  There is no difference in the API ether you configure NAT on T1 or T0 router. As @DRuggeri  pointed you can provide the T0 uuid which will configure the NAT rule on the T0 router.

**Comment by avoltmer** [comment] 2018-04-13 16:31
Looks like the issue is resolved so I am closing.

**Closed** 2018-04-14 00:57 UTC
Labels: enhancement
